/// A single message in an order-scoped customer ↔ driver conversation.
///
/// Plain immutable class (no codegen) — the conversation is ephemeral with the
/// order itself (rows cascade-delete with the order), so no freezed machinery
/// is warranted. [fromMap]/[toJson] mirror the `chat_messages` table columns.
class ChatMessage {
  const ChatMessage({
    required this.id,
    required this.orderId,
    required this.senderId,
    required this.body,
    this.createdAt,
  });

  /// UUID generated by Postgres (`gen_random_uuid()`); empty for messages not
  /// yet persisted (local echo).
  final String id;

  final String orderId;

  /// Profile id of the author — customer, driver, or support manager.
  final String senderId;

  /// Message text; enforced to 1..1000 chars by both Dart and DB CHECK.
  final String body;

  final DateTime? createdAt;

  static const int maxBodyLength = 1000;

  bool get isValidBody =>
      body.trim().isNotEmpty && body.trim().length <= maxBodyLength;

  factory ChatMessage.fromMap(Map<String, dynamic> map) {
    return ChatMessage(
      id: map['id']?.toString() ?? '',
      orderId: map['order_id']?.toString() ?? '',
      senderId: map['sender_id']?.toString() ?? '',
      body: map['body']?.toString() ?? '',
      createdAt: map['created_at'] == null
          ? null
          : DateTime.tryParse(map['created_at'].toString())?.toLocal(),
    );
  }

  Map<String, dynamic> toJson() => {
        if (id.isNotEmpty) 'id': id,
        'order_id': orderId,
        'sender_id': senderId,
        'body': body,
        if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
      };

  ChatMessage copyWith({
    String? id,
    String? orderId,
    String? senderId,
    String? body,
    DateTime? createdAt,
  }) {
    return ChatMessage(
      id: id ?? this.id,
      orderId: orderId ?? this.orderId,
      senderId: senderId ?? this.senderId,
      body: body ?? this.body,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          other.id == id &&
          other.orderId == orderId &&
          other.senderId == senderId &&
          other.body == body &&
          other.createdAt == createdAt;

  @override
  int get hashCode => Object.hash(id, orderId, senderId, body, createdAt);

  @override
  String toString() =>
      'ChatMessage(id: $id, orderId: $orderId, senderId: $senderId, '
      'createdAt: $createdAt)';
}
