-- ==============================================================================
-- Migration: Missing Features Schema (Cashier, Manager Ops, Customer, Inventory)
-- ==============================================================================

-- 1. Cashier POS: Cash Drawer Movements
CREATE TABLE IF NOT EXISTS public.cash_drawer_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    shift_id VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL, -- payIn, payOut, cashDrop, refund
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    reason TEXT NOT NULL,
    recipient_or_depositor TEXT,
    authorized_by_manager_pin VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Cashier POS: Held Orders Queue
CREATE TABLE IF NOT EXISTS public.held_orders (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    cashier_id UUID,
    cart_items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    custom_label TEXT,
    customer_phone VARCHAR(50),
    table_number INTEGER,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. Manager Dashboard: Operational Alerts
CREATE TABLE IF NOT EXISTS public.operational_alerts (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity VARCHAR(30) NOT NULL DEFAULT 'info', -- critical, warning, info
    category VARCHAR(50) NOT NULL DEFAULT 'system', -- inventory, kitchenDelay, delivery, system
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. Manager Dashboard: Staff Timesheets
CREATE TABLE IF NOT EXISTS public.staff_timesheets (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    user_id UUID NOT NULL,
    staff_name TEXT NOT NULL,
    role VARCHAR(50) NOT NULL,
    clock_in TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    clock_out TIMESTAMPTZ,
    break_minutes INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'onDuty', -- onDuty, onBreak, clockedOut
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. Manager Dashboard: Supplier Purchase Orders
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    supplier_name TEXT NOT NULL,
    supplier_phone VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'draft', -- draft, sentToSupplier, partiallyReceived, received, cancelled
    order_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    expected_delivery_date TIMESTAMPTZ,
    actual_delivery_date TIMESTAMPTZ,
    items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 6. Manager Dashboard: Guest Feedback Resolutions
CREATE TABLE IF NOT EXISTS public.guest_feedbacks (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    customer_name TEXT NOT NULL,
    customer_phone VARCHAR(50),
    order_id BIGINT,
    overall_rating INTEGER NOT NULL DEFAULT 5,
    food_quality_rating INTEGER NOT NULL DEFAULT 5,
    service_speed_rating INTEGER NOT NULL DEFAULT 5,
    cleanliness_rating INTEGER NOT NULL DEFAULT 5,
    comment TEXT,
    is_resolved BOOLEAN NOT NULL DEFAULT false,
    resolution_notes TEXT,
    compensation_coupon_code VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 7. Manager Dashboard: Sales Targets
CREATE TABLE IF NOT EXISTS public.sales_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    target_date DATE NOT NULL DEFAULT CURRENT_DATE,
    hourly_targets_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    daily_total_target NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 8. Customer: Dietary & Allergen Profile
CREATE TABLE IF NOT EXISTS public.customer_dietary_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    allergens TEXT[] NOT NULL DEFAULT '{}',
    dietary_goal VARCHAR(50) NOT NULL DEFAULT 'none',
    strict_allergen_alerts BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. Customer: Wallets & Gift Cards
CREATE TABLE IF NOT EXISTS public.customer_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.customer_wallet_transactions (
    id VARCHAR(100) PRIMARY KEY,
    wallet_id BIGINT REFERENCES public.customer_wallets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    title TEXT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    is_credit BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.gift_cards (
    id VARCHAR(100) PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    initial_balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    current_balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT true,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. Customer: Curbside Pickups
CREATE TABLE IF NOT EXISTS public.curbside_pickups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    customer_id UUID,
    car_model VARCHAR(100) NOT NULL,
    car_color VARCHAR(50) NOT NULL,
    license_plate VARCHAR(50) NOT NULL,
    parking_spot_note TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'onTheWay', -- onTheWay, arrivedOutside, deliveredToCar
    arrived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 11. Inventory: Recipes & Food Costing
CREATE TABLE IF NOT EXISTS public.recipes (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    menu_item_id VARCHAR(100) NOT NULL UNIQUE,
    menu_item_name TEXT NOT NULL,
    menu_item_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    ingredients_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    labor_cost NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    overhead_cost NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 12. Inventory: Waste Logs
CREATE TABLE IF NOT EXISTS public.waste_logs (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    ingredient_id VARCHAR(100) NOT NULL,
    ingredient_name TEXT NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    unit VARCHAR(30) NOT NULL DEFAULT 'كجم',
    cost_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    reason VARCHAR(50) NOT NULL, -- expired, spoiled, droppedOrDamaged, kitchenMistake, qualityControl
    custom_notes TEXT,
    logged_by VARCHAR(100) NOT NULL DEFAULT 'مدير الفرع',
    logged_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 13. Staff Shifts & Reconciliations (Waiters & Drivers)
CREATE TABLE IF NOT EXISTS public.shift_reconciliations (
    id VARCHAR(100) PRIMARY KEY,
    restaurant_id UUID NOT NULL DEFAULT '1e08b47c-15be-4604-a913-431af7fbd54f'::uuid,
    staff_id UUID NOT NULL,
    staff_name TEXT NOT NULL,
    role VARCHAR(50) NOT NULL,
    shift_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    opening_float NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    collected_cod NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    collected_tips NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total_sales_volume NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    tables_served_count INTEGER NOT NULL DEFAULT 0,
    completed_deliveries_count INTEGER NOT NULL DEFAULT 0,
    is_settled BOOLEAN NOT NULL DEFAULT false,
    settled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable RLS on all newly created tables
ALTER TABLE public.cash_drawer_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.held_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_timesheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_dietary_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gift_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curbside_pickups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.waste_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shift_reconciliations ENABLE ROW LEVEL SECURITY;

-- Permissive policies for authenticated & anon clients (matching project conventions)
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN 
        SELECT unnest(ARRAY[
            'cash_drawer_transactions',
            'held_orders',
            'operational_alerts',
            'staff_timesheets',
            'purchase_orders',
            'guest_feedbacks',
            'sales_targets',
            'customer_dietary_profiles',
            'customer_wallets',
            'customer_wallet_transactions',
            'gift_cards',
            'curbside_pickups',
            'recipes',
            'waste_logs',
            'shift_reconciliations'
        ])
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "%s_all_access" ON public.%I', tbl, tbl);
        EXECUTE format('CREATE POLICY "%s_all_access" ON public.%I FOR ALL TO public USING (true) WITH CHECK (true)', tbl, tbl);
    END LOOP;
END $$;
