import 'dart:async';

import 'package:supabase_flutter/supabase_flutter.dart';

import '../../../../config/supabase_config.dart';
import '../../../../core/errors/either.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/utils/logger.dart';
import '../../domain/entities/chat_message.dart';
import '../../domain/repositories/chat_repository.dart';

/// Supabase-backed [ChatRepository].
///
/// Reads/writes the `chat_messages` table and streams live inserts through a
/// Realtime Postgres-Changes channel scoped to one order (same per-table
/// subscription convention as `core/supabase/supabase_realtime_service.dart`).
class SupabaseChatRepository implements ChatRepository {
  SupabaseChatRepository({required SupabaseClient supabase})
    : _supabase = supabase;

  final SupabaseClient _supabase;

  static final RegExp _uuidRegex = RegExp(
    r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
  );

  static String? _sanitizeUuid(String? input) {
    if (input == null || input.isEmpty) return null;
    if (_uuidRegex.hasMatch(input)) return input;
    return null;
  }

  @override
  Future<Either<Failure, ChatMessage>> send(ChatMessage message) async {
    // order_id is TEXT in Postgres and app-generated order ids are NOT UUIDs
    // (e.g. 'ORD-0001'), so only require a non-empty value here — the FK to
    // orders(id) enforces existence server-side. sender_id must be a real
    // profiles uuid, though.
    final orderId = message.orderId.trim();
    final senderId = _sanitizeUuid(message.senderId);
    if (orderId.isEmpty || senderId == null) {
      return const Left<Failure, ChatMessage>(
        ValidationFailure('معرّفات المحادثة غير صالحة للإرسال للسيرفر'),
      );
    }
    if (!message.isValidBody) {
      return const Left<Failure, ChatMessage>(
        ValidationFailure('الرسالة فارغة أو تتجاوز الحد الأقصى للطول'),
      );
    }
    try {
      final parsedOrderId = int.tryParse(orderId) ?? orderId;
      // Insert without id/created_at — both are generated by Postgres.
      final response = await _supabase
          .from(SupabaseConfig.chatMessagesTable)
          .insert({
            'order_id': parsedOrderId,
            'sender_id': senderId,
            'body': message.body,
          })
          .select()
          .limit(1);
      final rows = response as List;
      if (rows.isEmpty) {
        return Right<Failure, ChatMessage>(message);
      }
      return Right<Failure, ChatMessage>(
        ChatMessage.fromMap(Map<String, dynamic>.from(rows.first as Map)),
      );
    } catch (e) {
      AppLogger.error(
        'Supabase send chat message error: $e '
        '(orderId=${message.orderId}, senderId=${message.senderId})',
      );
      return Left<Failure, ChatMessage>(ServerFailure('فشل إرسال الرسالة: $e'));
    }
  }

  /// Loads the conversation history for an order, oldest first.
  ///
  /// Capped at the newest [ChatRepository.historyPageSize] messages: the
  /// query fetches newest-first (DESC + LIMIT) for efficiency, then the rows
  /// are reversed to preserve the oldest-first contract.
  @override
  Future<Either<Failure, List<ChatMessage>>> history(String orderId) async {
    try {
      // order_id is TEXT; any non-empty id is queryable (see send()).
      final sanitized = orderId.trim();
      if (sanitized.isEmpty) {
        return const Right<Failure, List<ChatMessage>>([]);
      }
      final response = await _supabase
          .from(SupabaseConfig.chatMessagesTable)
          .select()
          .eq('order_id', sanitized)
          .order('created_at', ascending: false)
          .limit(ChatRepository.historyPageSize);
      final messages = (response as List)
          .map(
            (raw) => ChatMessage.fromMap(Map<String, dynamic>.from(raw as Map)),
          )
          .toList();
      return Right<Failure, List<ChatMessage>>(messages.reversed.toList());
    } catch (e) {
      AppLogger.error('Supabase chat history error: $e (orderId=$orderId)');
      return Left<Failure, List<ChatMessage>>(
        ServerFailure('فشل جلب سجل المحادثة: $e'),
      );
    }
  }

  /// History-first live feed: the fetched snapshot is emitted as soon as it
  /// arrives, then every matching insert event appends to the buffer.
  ///
  /// The Realtime channel follows the same per-table subscription convention
  /// used by `SupabaseRealtimeService.subscribe()`, narrowed to this order via
  /// an `order_id=eq.` filter; cancellation removes the channel.
  @override
  Stream<List<ChatMessage>> watch(String orderId) {
    late final StreamController<List<ChatMessage>> out;
    final buffer = <ChatMessage>[];
    var closed = false;
    RealtimeChannel? channel;

    void emit() {
      if (closed) return;
      out.add(List.unmodifiable(buffer));
    }

    out = StreamController<List<ChatMessage>>(
      onListen: () async {
        // 1. History snapshot first.
        final result = await history(orderId);
        result.when(
          onLeft: (_) {
            /* live events still flow below */
          },
          onRight: (rows) {
            buffer
              ..clear()
              ..addAll(rows);
            emit();
          },
        );

        // 2. Live inserts for this order only.
        try {
          channel = _supabase
              .channel(
                'public:${SupabaseConfig.chatMessagesTable}:'
                'order_id=eq.$orderId',
              )
              .onPostgresChanges(
                event: PostgresChangeEvent.insert,
                schema: 'public',
                table: SupabaseConfig.chatMessagesTable,
                filter: PostgresChangeFilter(
                  type: PostgresChangeFilterType.eq,
                  column: 'order_id',
                  value: orderId,
                ),
                callback: (payload) {
                  final message = ChatMessage.fromMap(
                    Map<String, dynamic>.from(payload.newRecord),
                  );
                  // send()'s realtime echo can duplicate a locally merged
                  // message — dedupe by primary key.
                  if (buffer.any((m) => m.id == message.id)) return;
                  buffer.add(message);
                  emit();
                },
              )
              .subscribe();
        } catch (e) {
          AppLogger.error(
            'Supabase chat watch subscribe error: $e (orderId=$orderId)',
          );
        }
      },
      onCancel: () async {
        closed = true;
        final ch = channel;
        channel = null;
        if (ch != null) {
          try {
            await _supabase.removeChannel(ch);
          } catch (e) {
            AppLogger.warning('Supabase chat watch unsubscribe error: $e');
          }
        }
        await out.close();
      },
    );
    return out.stream;
  }
}
